// Copies the offline OCR engine into public/tesseract so the app never calls a CDN.
// Runs automatically after `npm install`.
import { mkdir, copyFile, access, writeFile } from 'node:fs/promises'
import { createWriteStream } from 'node:fs'
import { Readable } from 'node:stream'
import { pipeline } from 'node:stream/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'public', 'tesseract')

// The engine picks a build to match the browser, so ship every LSTM variant.
const CORE_FILES = [
  'tesseract-core-lstm.js', 'tesseract-core-lstm.wasm', 'tesseract-core-lstm.wasm.js',
  'tesseract-core-simd-lstm.js', 'tesseract-core-simd-lstm.wasm', 'tesseract-core-simd-lstm.wasm.js',
  'tesseract-core-relaxedsimd-lstm.js', 'tesseract-core-relaxedsimd-lstm.wasm', 'tesseract-core-relaxedsimd-lstm.wasm.js',
]

const COPIES = [
  ['node_modules/tesseract.js/dist/worker.min.js', 'worker.min.js'],
  ...CORE_FILES.map((f) => [`node_modules/tesseract.js-core/${f}`, f]),
]

const LANG_URL = 'https://cdn.jsdelivr.net/npm/@tesseract.js-data/eng/4.0.0_best_int/eng.traineddata.gz'

const exists = async (p) => { try { await access(p); return true } catch { return false } }

await mkdir(out, { recursive: true })

for (const [from, to] of COPIES) {
  const src = join(root, from)
  if (!(await exists(src))) {
    console.warn(`[setup-ocr] missing ${from} — run npm install first`)
    continue
  }
  await copyFile(src, join(out, to))
}

const lang = join(out, 'eng.traineddata.gz')
if (await exists(lang)) {
  console.log('[setup-ocr] language data already present')
} else {
  try {
    const res = await fetch(LANG_URL)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    await pipeline(Readable.fromWeb(res.body), createWriteStream(lang))
    console.log('[setup-ocr] downloaded English language data')
  } catch (err) {
    console.warn(`[setup-ocr] could not download language data: ${err.message}`)
    console.warn(`[setup-ocr] download it by hand into public/tesseract/eng.traineddata.gz from ${LANG_URL}`)
  }
}

await writeFile(join(out, 'README.txt'),
  'Generated by scripts/setup-ocr.mjs. Do not edit or commit. Delete and re-run `npm run setup:ocr` to rebuild.\n')
console.log('[setup-ocr] done')
